# Pages placed under these sections will be shown on the homepage and archive page.
mainSections = ["post"]

# Output page's full content in RSS.
rssFullContent = true
favicon = "/favicon.png"

[footer]
since = 2020
customText = ""

[dateFormat]
published = "Jan 02, 2006"
lastUpdated = "Jan 02, 2006 15:04 MST"

[sidebar]
emoji = "🎯"
subtitle = "Project by Keivan Tafakkori, PhD Candidate of Industrial Engineering @ University of Tehran"

[sidebar.avatar]
enabled = true
local = true
src = "img/feloop.png"

[article]
math = false
readingTime = true

[article.license]
enabled = true
default = "Author: Keivan Tafakkori. All Rights Reserved."

## Widgets
[[widgets.homepage]]
type = "search"

[[widgets.homepage]]
type = "archives"

[widgets.homepage.params]
limit = 5

[[widgets.homepage]]
type = "categories"

[widgets.homepage.params]
limit = 10

[[widgets.homepage]]
type = "tag-cloud"

[widgets.homepage.params]
limit = 10

[[widgets.page]]
type = "toc"

[opengraph.twitter]
site = "KTafakkori"  # Replace with your Twitter handle
card = "summary_large_image"

[defaultImage.opengraph]
enabled = false
local = false
src = ""

[colorScheme]
toggle = true
default = "auto"

[imageProcessing.cover]
enabled = true

[imageProcessing.content]
enabled = true

## Comments
[comments]
enabled = true
provider = "utterances"

[comments.utterances]
repo = "ktafakkori/ktafakkori.github.io"
issueTerm = "pathname"
label = ""
