site_name: FELOOP
site_url: https://ktafakkori.github.io/
nav:
  - Home: index.md
  - Blog:
    - blog/index.md
    - blog/authors.md
theme:
 name: material
 features:
    - navigation.indexes
    - navigation.instant.prefetch
 logo: assets/logo/logo.png
 favicon: assets/logo/favicon.png
 icon:
  previous: fontawesome/solid/angle-left
  next: fontawesome/solid/angle-right
  
 palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - blog

extra:
  alternate:
    - name: English
      link: /en/ 
      lang: en
    - name: Persian
      link: /fa/
      lang: fa
