authors:
  ktafakkori:
    name: Keivan Tafakkori
    description: Creator of FelooPy
    avatar: https://media.licdn.com/dms/image/D4D03AQELu0bZpXapYw/profile-displayphoto-shrink_400_400/0/1708118243900?e=1715212800&v=beta&t=k4loQM8J4YySuqT3YoFPptIRCHiHiq7HFZjILLVDmLk
